### ISSUE TITLE
Color Picker: setting values with the api does not fire any events

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#113] opened 2016-01-20 09:02 UTC
The usual component change event has a cause field with "user" and "api". However programatically changing the color picker doesn't seem to trigger the change or changeend events.

Consider:

```
hx.select('body').add(hx.colorPicker().attr('id', 'apiEvents').classed('hx-btn', true))
hx.component(apiEvents).on('change', (p) => console.log(p)).on('changeend', (p) => console.log(p)).value('#ddd')
```

Nothing is logged.

**Comment by c-frater** [comment] 2016-01-21 13:14
I'd expect it to fire the `change` event with the cause of `api`. 
This might be a 2.0.0 change as the events currently emit the color and not an event in the format of 
```js
{
  cause: 'user',
  value: ...
}
```

**Comment by c-frater** [comment] 2018-07-03 12:37
Closing as we are removing the colour picker module in #454

**Closed by c-frater** 2018-07-03 12:37 UTC
Labels: Bug
