### ISSUE TITLE
Number Picker: disable the decrement/increment buttons when the value is at the min/max

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#159] opened 2016-03-07 17:15 UTC
This involves adding/removing the disabled attribute to the buttons when the value changes - currently the buttons just ignore input when they hit the limits

**Comment by c-frater** [comment] 2016-03-08 08:30
Duplicate of #150 ?

**Comment by jmsmyth** [comment] 2016-03-08 09:20
Slightly different - I've added more of a description

**Comment by c-frater** [comment] 2016-03-08 09:24
Makes sense now :)

**Closed** 2016-10-13 09:41 UTC
Labels: Easy To Do, Enhancement, For New Contributors, In Review
